import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsCommunity: SidebarsConfig = {
  communitySidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebarsCommunity;
