import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebarsCertifications: SidebarsConfig = {
  communitySidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebarsCertifications
;